name: Generate Site Metrics

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate speed metrics
        uses: lowlighter/metrics@latest
        with:
            filename: images/speed-metrics.svg
            token: NOT_NEEDED
            base: ""
            config_timezone: America/Fortaleza
            plugin_pagespeed: yes
            plugin_pagespeed_url: https://luanroger.github.io/ong-tiniebird-cats
